networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-volume:

services:
  mysql-app:
    image: mysql:latest
    container_name: mysql-app
    environment:
      MYSQL_ROOT_PASSWORD: andhikad
      MYSQL_DATABASE: library
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
    networks:
      - mysql-network

  golang-app:
    image: anotherdanger/golang-app:latest
    container_name: golang-app
    environment:
      - DB_URL=root:andhikad@tcp(mysql-app:3306)/library
    expose:
      - 8080
    ports:
      - 8080:8080
    
    networks:
      - mysql-network
    